---
- hosts: grupo2
  become: true
  tasks:
    - name: crear archivo
      copy:
        content: "123"
        dest: /root/123.txt
      register: file

    - name: debug
      debug:
        var: file
...
