---
- hosts: grupo2
  become: true
  tasks:
    - name: servicio
      systemd:
        name: httpd
        state: started
        enabled: true
      register: srv
    - name: debug servicio
      debug: 
        var: srv
...
