---
- hosts: grupo3
  become: true
  vars_files: 
    - crypt1.yml
  tasks:
    - name: Instalar {{ paquetes }}
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ paquetes }}"
...
