---
- name: Install epel-release on CentOS
  yum: name=epel-release state=installed
  when: ansible_distribution == 'CentOS'

- name: Install epel-release on RedHat
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=installed
  when: ansible_distribution == 'RedHat'

- name: Check IPv6
  assert:
    that:
      - (ansible_all_ipv6_addresses is defined and ansible_all_ipv6_addresses|length>0)
      - nginx_server_tokens in ['on', 'off', 'build']
    msg: "Check your ipv6 configuration"
  when: nginx_ipv6

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Nginx default config
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: nginx_default_conf
  notify: reload nginx

- name: Create working directory
  file:
    path: "{{ nginx_default_root }}"
    state: directory
    setype: httpd_sys_content_t

- name: Check modules
  file:
    path: "{{ item }}"
    state: file
  with_items: "{{ nginx_modules }}"

- name: Open Firewall
  firewalld:
    port: 80/tcp
    immediate: true
    permanent: true
    state: enabled

- name: Start/enable nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Sample content
  copy:
    content: "Hello NGINX"
    dest: "{{ nginx_default_root }}/index.html"
  notify: reload nginx
...
