---
  - name: "Ensure nodev/nosuid/noexec option set on /tmp partition"
    template:
      src: etc/systemd/system/tmp.mount.j2
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: 0644
    notify: systemd restart tmp.mount
    with_items: "{{ ansible_mounts }}"
    when:
      - item.mount == '/tmp'
      - item.fstype == 'xfs'
      - ansible_distribution_major_version == "7"

  - name: "Ensure separate partition exists for /tmp | enable and start/restart tmp.mount"
    systemd:
        name: tmp.mount
        daemon_reload: yes
        enabled: yes
        masked: no
        state: started
    with_items: "{{ ansible_mounts }}"
    when:
      - item.mount == '/tmp'
      - ansible_distribution_major_version == "7"

  - name: "Ensure nodev/nosuid/noexec option set on /var/tmp partition"
    template:
      src: etc/systemd/system/var-tmp.mount.j2
      dest: /etc/systemd/system/var-tmp.mount
      owner: root
      group: root
      mode: 0644
    notify: systemd restart vartmp.mount
    with_items: "{{ ansible_mounts }}"
    when:
      - item.mount == '/var/tmp'
      - item.fstype == 'xfs'
      - ansible_distribution_major_version == "7"

  - name: "Ensure separate partition exists for /var/tmp | enable and start/restart /var/tmp mount point"
    systemd:
        name: var-tmp.mount
        daemon_reload: yes
        enabled: yes
        masked: no
        state: started
    with_items: "{{ ansible_mounts }}"
    when:
      - item.mount == '/var/tmp'
      - ansible_distribution_major_version == "7"
